### PR TITLE
Re-build

### PR DESCRIPTION
**Pull request by diasdm**
Re-build needed due to https://movai.atlassian.net/browse/DP-856

### CODE REVIEW

**Review by MithunKinarullathil — APPROVED** [review]

**Review by AlexFernandes-MOVAI — APPROVED** [review]
seems valid, do we need need to integrate those new packages in CE new release ?

**Comment by diasdm** [comment]
On my side I don't see a reason for us not to, @MithunKinarullathil?

**Comment by MithunKinarullathil** [comment]
I don't see a new pre-release, I think the pipeline broke. We can release it by making the pre-release -> release process, as this package is installed on runtime and not mentioned anywhere with a version number.

**Comment by AlexFernandes-MOVAI** [comment]
I will have a check on this, the workflow referenced does not exist anymore

**Pull request merged**
